# -*- coding: utf-8 -*-
{
    'name': "Recurring Subscription",
    'version': "19.0.1.0",
    'summary': """Recurring Subscription""",
    'description': """Recurring Subscription""",
    'author': "Cybrosys Techno Solution",
    'website': "www.cybrosys.com",
    'category': "Recurring Subscription",
    'license': "LGPL-3",
    'depends': ['base','sale_management','mail','contacts','account',],
    'post_init_hook': 'post_init_hook',
    'sequence': -10,
    'application': True,
    'installable': True,
    'auto_install': False,
    'data': [
        "security/ir.model.access.csv",
        "data/recurring_subscription_data.xml",
        "data/account_id.xml",
        "data/product_data.xml",
        "data/ir_cron_data.xml",
        "views/res_partner_views.xml",
        "views/crm_views.xml",
        "views/recurring_subscription_views.xml",
        "views/subscription_credit_views.xml",
        "views/billing_schedule_views.xml",
        "views/partner_account_views.xml",
        "views/recurring_subscription_menus.xml",
    ]
}