# -*- coding: utf-8 -*-
{
    'name': "Recurring Subscription",
    'version': "19.0.1.0.0",
    'summary': """Recurring Subscription""",
    'description': """Recurring Subscription""",
    'author': "Cybrosys Techno Solution",
    'website': "www.cybrosys.com",
    'category': "Recurring Subscription",
    'license': "LGPL-3",
    'depends': ['base', 'sale_management', 'mail', 'contacts', 'account', 'crm',
                'web', 'website'],
    'sequence': -10,
    'application': True,
    'installable': True,
    'auto_install': False,
    'data': [
        "security/subscription_rule.xml",
        "security/security_group.xml",
        "security/ir.model.access.csv",
        "data/recurring_subscription_data.xml",
        "data/account_id.xml",
        "data/product_data.xml",
        "data/ir_cron_data.xml",
        "data/email_template.xml",
        "data/ir_action_mail.xml",
        "wizard/recurring_subscription_report_view.xml",
        "wizard/recurring_credit_report_view.xml",
        "report/subscription_report_views.xml",
        "report/subscription_report_template.xml",
        "report/credit_report_views.xml",
        "report/credit_report_template.xml",
        'views/recurring_subscription_page.xml',
        'views/recurring_credit_page.xml',
        "views/billing_schedule_page.xml",
        "views/res_partner_views.xml",
        "views/crm_views.xml",
        "views/account_move.xml",
        "views/recurring_subscription_views.xml",
        "views/subscription_credit_views.xml",
        "views/billing_schedule_views.xml",
        "views/partner_account_views.xml",
        "views/recurring_subscription_menus.xml",
        'views/snippets/category_template.xml', ],
    'assets': {
        'web.assets_backend': [
            'recurring_subscription/static/src/js/action_manager.js', ],
        'web.assets_frontend': [
            'recurring_subscription/static/src/js/multiple.js',
            '/recurring_subscription/static/src/xml/category_highlight_content.xml',
            '/recurring_subscription/static/src/js/product_category.js', ],
    },
}
